services:
  database:
    container_name: solpay-postgres
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./databasepg:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d solpay"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - solpay-network

  solpay-core-service:
    container_name: solpay-core-service
    restart: on-failure
    image: solpay-core-service:latest
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: solpay-postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      APP_PORT: ${APP_PORT}
      MQ_HOST: solpay-rabbitmq
      MQ_PORT: ${MQ_PORT}
      MQ_USER: ${MQ_USER}
      MQ_PASSWORD: ${MQ_PASSWORD}
      MQ_VHOST: ${MQ_VHOST}
      MQ_URL: amqp://${MQ_USER}:${MQ_PASSWORD}@solpay-rabbitmq:${MQ_PORT}/${MQ_VHOST}
      SWAP_SERVICE_PORT: ${SWAP_SERVICE_PORT}
      SWAP_SERVICE_URL: http://solpay-swap-service:${SWAP_SERVICE_PORT}/api/v1
    networks:
      - solpay-network

  blockchain-queue:
    container_name: solpay-blockchain-service
    image: solpay-blockchain-service:latest
    environment:
      APP_PORT: 8009
      MQ_HOST: solpay-rabbitmq
      MQ_USER: ${MQ_USER}
      MQ_PASSWORD: ${MQ_PASSWORD}
      MQ_VHOST: ${MQ_VHOST}
      MQ_URL: amqp://${MQ_USER}:${MQ_PASSWORD}@solpay-rabbitmq/${MQ_VHOST}
    ports:
      - "8009:8009"
    networks:
      - solpay-network

  solpay-swap-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solpay-swap-service
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - RPC_URL=${RPC_URL}
    restart: unless-stopped
    networks:
      - solpay-core-service_solpay-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: solpay-rabbitmq
    ports:
      - "5672:5672" # พอร์ตสำหรับเชื่อมต่อรับ-ส่งข้อมูล (AMQP)
      - "15672:15672" # พอร์ตสำหรับหน้า Dashboard (RabbitMQ Management)
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASSWORD:-guest}
      RABBITMQ_DEFAULT_VHOST: ${MQ_VHOST:-/}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - solpay-network

networks:
  solpay-network:
    driver: bridge
